################ Application Configuration ################
spring.application.name=${APPLICATION_NAME:user-service}
server.port=${SERVER_PORT:9001}

################# MongoDB Configuration ##################
spring.data.mongodb.host=${MONGODB_HOST:cluster0.2ug2juv.mongodb.net}
spring.data.mongodb.port=${MONGODB_PORT:27017}
spring.data.mongodb.username=${MONGODB_USERNAME:dkumawat7627}
spring.data.mongodb.password=${MONGODB_PASSWORD:Admin%40123}
spring.data.mongodb.database=${MONGODB_DATABASE:Banking-System}
spring.data.mongodb.options=${MONGODB_OPTIONS:retryWrites=true&w=majority&appName=Cluster0&ssl=true}
spring.data.mongodb.uri=mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}/${spring.data.mongodb.database}?${spring.data.mongodb.options}

commonlib.service.environment=dev
commonlib.service.name=user-service